# Generated by Django 3.2 on 2021-08-12 07:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(default=False, upload_to=accounts.models.CustomUser.path_and_rename),
        ),
    ]
